"""
app.py — Gradio demo + pipeline walkthrough for the name-to-nationality classifier.

This Space is organized as one page per pipeline stage, mirroring pipeline/:
  1. EDA          (pipeline/eda01.py)        — explore the data
  2. Preprocess   (pipeline/preprocess02.py) — build the dataset & splits
  3. Baselines    (pipeline/baseline03.py)   — train sklearn floor models
  4. Evaluation   (pipeline/evaluation04.py) — score on the held-out test set
  5. Predict      (pipeline/predict05.py)    — live inference (single + batch)

Each stage page has a "Run this step" button that *simulates* the (slow, offline)
pipeline run by streaming a realistic console log, then reveals the PRE-GENERATED
artifacts (plots, metrics, reports) bundled under assets/. The Predict page is the
only one that runs for real — inference is fast on CPU.

Preprocessing is imported from common.py, so it is byte-identical to training.

ETHICS: nationality predicted from a name is a STATISTICAL GUESS over romanized
character patterns, NOT a fact about any individual. Do not use for profiling,
hiring, credit, immigration, or law-enforcement decisions. Submitted names are not
logged or stored.
"""

from __future__ import annotations

import json
import os
import pickle
import tempfile
import time

import numpy as np
import pandas as pd
import gradio as gr

from common import normalize_name, name_to_indices

MODEL_DIR = os.environ.get("MODEL_DIR", "models")
ASSETS = os.environ.get("ASSETS_DIR", "assets")
COUNTRY_CODES = os.environ.get("COUNTRY_CODES", "country_codes.csv")

# backend label -> sklearn model file (loaded with a shared TF-IDF vectorizer).
BACKENDS = {
    "Logistic Regression": "baseline_logreg.pkl",
    "Linear SVM":          "baseline_linsvm.pkl",
    "SGD (modified Huber)": "baseline_sgd.pkl",
}
DEFAULT_BACKEND = "Logistic Regression"

DISCLAIMER = (
    "⚠️ **Statistical guess only.** This predicts likely countries from the *character "
    "patterns* of a romanized name — it is **not** a statement about any real person's "
    "nationality, ethnicity, or origin. Many names span multiple countries. **Do not use "
    "for profiling, hiring, credit, immigration, or law-enforcement decisions.** Names you "
    "enter are not logged or stored."
)


# ====================================================================================
# Artifact loading (pre-generated by the offline pipeline, bundled under assets/)
# ====================================================================================
def _asset(*parts: str) -> str:
    return os.path.join(ASSETS, *parts)


def _load_json(path: str) -> dict:
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def _read_text(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except OSError:
        return ""


EDA_SUMMARY = _load_json(_asset("eda", "eda_summary.json"))
EDA_REPORT = _read_text(_asset("eda", "eda_report.md"))
PRE_STATS = _load_json(_asset("preprocess", "preprocess_stats.json"))
BASE_TRAIN = _load_json(_asset("baseline", "baseline_metrics.json"))
EVAL = _load_json(_asset("evaluation", "baseline_eval_metrics.json"))


def _pct(x) -> str:
    try:
        return f"{float(x) * 100:.1f}%"
    except (TypeError, ValueError):
        return "—"


def _load_country_names() -> dict:
    for p in (COUNTRY_CODES, os.path.join("archive", "country_codes.csv")):
        if os.path.exists(p):
            df = pd.read_csv(p)
            return dict(zip(df["country_code"].astype(str), df["country_name"].astype(str)))
    return {}


COUNTRY_NAMES = _load_country_names()


# ====================================================================================
# Live inference backends (Predict page)
# ====================================================================================
class SklearnPredictor:
    def __init__(self, path: str):
        with open(path, "rb") as f:
            self.model = pickle.load(f)
        with open(os.path.join(MODEL_DIR, "vectorizer.pkl"), "rb") as f:
            self.vec = pickle.load(f)
        with open(os.path.join(MODEL_DIR, "label_map.json"), encoding="utf-8") as f:
            self.label_map = {int(k): v for k, v in json.load(f).items()}

    def predict_probs(self, name: str) -> dict:
        X = self.vec.transform([normalize_name(name)])
        classes = self.model.classes_
        if hasattr(self.model, "predict_proba"):
            probs = self.model.predict_proba(X)[0]
        else:  # LinearSVC -> softmax over decision_function
            scores = self.model.decision_function(X)[0]
            e = np.exp(scores - scores.max())
            probs = e / e.sum()
        return {self.label_map[int(classes[i])]: float(probs[i]) for i in range(len(classes))}


_CACHE: dict = {}


def get_predictor(backend: str):
    """Lazy-load and cache a backend so cold start only pays for what's used."""
    if backend not in _CACHE:
        path = os.path.join(MODEL_DIR, BACKENDS[backend])
        _CACHE[backend] = SklearnPredictor(path)
    return _CACHE[backend]


def _code_to_display(cc: str) -> str:
    name = COUNTRY_NAMES.get(cc, cc)
    return f"{name} ({cc})" if name != cc else cc


def predict_single(name: str, backend: str, top_k: int):
    norm = normalize_name(name or "")
    if not norm:
        return {"⚠️ name has no a–z characters after normalization": 1.0}, ""
    probs = get_predictor(backend).predict_probs(name)
    top = sorted(probs.items(), key=lambda kv: kv[1], reverse=True)[: int(top_k)]
    label_out = {_code_to_display(cc): p for cc, p in top}
    info = f"Normalized input: `{norm}`  •  backend: {backend}"
    return label_out, info


def predict_batch(file, backend: str, top_k: int):
    if file is None:
        return None, None, "Upload a CSV with a column of names first."
    df = pd.read_csv(file.name)
    name_col = "name" if "name" in df.columns else df.columns[0]
    predictor = get_predictor(backend)

    rows = []
    for raw in df[name_col].astype(str).tolist():
        norm = normalize_name(raw)
        if not norm:
            rows.append({"name": raw, "normalized": "", "top1_code": "", "top1_country": "",
                         "top1_prob": "", "top_k": ""})
            continue
        probs = predictor.predict_probs(raw)
        ranked = sorted(probs.items(), key=lambda kv: kv[1], reverse=True)[: int(top_k)]
        cc1, p1 = ranked[0]
        rows.append({
            "name": raw,
            "normalized": norm,
            "top1_code": cc1,
            "top1_country": COUNTRY_NAMES.get(cc1, cc1),
            "top1_prob": round(p1, 4),
            "top_k": "; ".join(f"{cc}:{p:.3f}" for cc, p in ranked),
        })
    out = pd.DataFrame(rows)
    tmp = tempfile.NamedTemporaryFile(prefix="predictions_", suffix=".csv", delete=False)
    out.to_csv(tmp.name, index=False, encoding="utf-8")
    msg = f"Predicted {len(out):,} names using **{name_col}** column • backend: {backend}"
    return out, tmp.name, msg


# ====================================================================================
# "Run this step" simulation — stream a console log, then reveal the artifacts
# ====================================================================================
def make_runner(log_lines):
    """Return a generator that streams `log_lines` to a console box, then reveals
    the (pre-generated) artifacts group. Outputs: [console, artifacts_group]."""
    def run():
        acc = ""
        # opening banner is instant
        for i, line in enumerate(log_lines):
            acc += line + "\n"
            # commands / blank lines flash by; work lines get a small pause
            delay = 0.05 if line.startswith("$") or not line.strip() else 0.28
            time.sleep(delay)
            # reveal the console (hidden until first click) and stream into it
            yield gr.update(value=acc, visible=True), gr.update()
        acc += "\n✓ step complete — showing pre-generated artifacts below.\n"
        yield gr.update(value=acc, visible=True), gr.update(visible=True)
    return run


def step_console():
    # hidden until the Run button is clicked (the runner reveals it)
    return gr.Code(label="console", value="", interactive=False, lines=10, visible=False,
                   elem_classes="console")


# ---- per-step simulated logs (numbers are the real pipeline outputs) ---------------
EDA_LOG = [
    "$ python -m pipeline.eda01 --out_dir eda/",
    "[eda] scanning archive/forenames.csv (chunked) … 12,443,052 rows / 104 countries",
    "[eda] scanning archive/surnames.csv  (chunked) … 21,079,771 rows / 104 countries",
    "[eda] profiling splits: train=3,624,986  val=776,782  test=776,784",
    "[eda] class balance: 104 classes, imbalance 1.75× (AE=35,000 … KH=19,986)",
    "[eda] name length: mean 13.22 chars, p95=19 (cap max_len=30)",
    "[eda] multi-country names: 174,564  (mean breadth 2.71, max 30 → 'ali ali')",
    "[eda] wrote 8 figures + eda_report.md + eda_summary.json",
]

PRE_LOG = [
    "$ python -m pipeline.preprocess02 --max_per_country 50000",
    "[pre] reading aggregated tables (chunked) …",
    "[pre] accumulated per-country token counts (top-K pruned to bound RAM)",
    "[pre] synthesizing full names: forename ⨯ surname weighted by real frequency",
    "[pre] stratified 70/15/15 split per country",
    "[pre] built name_country_map.json — 174,564 multi-country names",
    "[pre] train augmentation: 0 added (imbalance already ≈1.8×)",
    "[pre] featurized to int index arrays (max_len=30)",
    "[pre] train=3,624,986  val=776,782  test=776,784  classes=104",
]

BASE_LOG = [
    "$ python -m pipeline.baseline03",
    "[base] TF-IDF char n-grams over 3.6M synthesized names …",
    "[base] fit LogisticRegression(saga) …   169.1s   val macro-F1=0.501",
    "[base] fit LinearSVC …                   485.6s   val macro-F1=0.494",
    "[base] fit SGD(modified_huber) …           9.5s   val macro-F1=0.478",
    "[base] pickled 3 models + shared TF-IDF vectorizer",
]

EVAL_LOG = [
    "$ python -m pipeline.evaluation04",
    "[eval] loading held-out test split (776,784 names) …",
    "[eval] logreg : macro-F1=0.501  acc=0.511  top3=0.693  top5=0.771  MRR=0.629",
    "[eval] linsvm : macro-F1=0.495  acc=0.513  top3=0.679  top5=0.749  MRR=0.622",
    "[eval] sgd    : macro-F1=0.478  acc=0.500  top3=0.673  top5=0.746  MRR=0.611",
    "[eval] ambiguity-aware (set-lenient) top1=0.551 logreg  (+0.041 vs strict acc)",
    "[eval] wrote per-country F1 + confusion + model-comparison plots",
]


# ====================================================================================
# Narration + artifact markdown builders
# ====================================================================================
def _stat_cards(pairs) -> str:
    """Render label/value pairs as a row of styled HTML 'stat cards'."""
    cards = "".join(
        f'<div class="stat"><div class="v">{v}</div><div class="k">{k}</div></div>'
        for k, v in pairs
    )
    return f'<div class="stat-cards">{cards}</div>'


def _no_data(msg: str) -> str:
    return f'<p class="muted">{msg}</p>'


def eda_stats_html() -> str:
    s = EDA_SUMMARY.get("splits", {})
    raw = EDA_SUMMARY.get("raw", {})
    if not s:
        return _no_data("EDA summary not found.")
    return _stat_cards([
        ("Countries", s.get("num_classes", "—")),
        ("Forename rows", f"{raw.get('forenames_rows', 0):,}"),
        ("Surname rows", f"{raw.get('surnames_rows', 0):,}"),
        ("Imbalance", f"{s.get('train_imbalance_ratio', '—')}×"),
        ("Multi-country names", f"{s.get('n_multi_country_names', 0):,}"),
    ])


def pre_stats_html() -> str:
    s = PRE_STATS
    if not s:
        return _no_data("Preprocess stats not found.")
    return _stat_cards([
        ("Classes", s.get("num_classes", "—")),
        ("Train", f"{s.get('n_train', 0):,}"),
        ("Val", f"{s.get('n_val', 0):,}"),
        ("Test", f"{s.get('n_test', 0):,}"),
        ("Cap / country", f"{s.get('max_per_country', 0):,}"),
        ("Imbalance", f"{s.get('post_split_train_imbalance_ratio', '—')}×"),
    ])


def baseline_table_md() -> str:
    if not BASE_TRAIN:
        return "_Baseline metrics not found._"
    names = {"logreg": "Logistic Regression", "linsvm": "Linear SVM", "sgd": "SGD (mod. Huber)"}
    rows = ["| Model | Val macro-F1 | Test macro-F1 | Test acc | Train time |",
            "| --- | --- | --- | --- | --- |"]
    for key in ("logreg", "linsvm", "sgd"):
        m = BASE_TRAIN.get(key, {})
        val, test = m.get("val", {}), m.get("test", {})
        rows.append(
            f"| {names[key]} | {val.get('macro_f1', 0):.3f} | {test.get('macro_f1', 0):.3f} "
            f"| {_pct(test.get('accuracy'))} | {m.get('train_seconds', 0):.0f}s |"
        )
    return "\n".join(rows)


def eval_table_md() -> str:
    if not EVAL:
        return "_Evaluation metrics not found._"
    names = {"logreg": "Logistic Regression", "linsvm": "Linear SVM", "sgd": "SGD (mod. Huber)"}
    rows = ["| Model | macro-F1 | Acc | Top-3 | Top-5 | MRR | Set-lenient top-1 |",
            "| --- | --- | --- | --- | --- | --- | --- |"]
    for key in ("logreg", "linsvm", "sgd"):
        m = EVAL.get(key, {})
        s = m.get("strict", {})
        a = m.get("ambiguity_aware", {})
        rows.append(
            f"| {names[key]} | **{s.get('macro_f1', 0):.3f}** | {_pct(s.get('accuracy'))} "
            f"| {_pct(s.get('top3'))} | {_pct(s.get('top5'))} | {s.get('mrr', 0):.3f} "
            f"| {_pct(a.get('set_lenient_top1'))} |"
        )
    return "\n".join(rows)


def per_country_md() -> str:
    pc = EVAL.get("logreg", {}).get("per_country_f1", {})
    if not pc:
        return ""
    ranked = sorted(pc.items(), key=lambda kv: kv[1], reverse=True)
    best, worst = ranked[:8], ranked[-8:]

    def line(items):
        return " · ".join(f"{_code_to_display(cc)} {f1:.2f}" for cc, f1 in items)

    return (f"**Easiest countries (logreg F1):** {line(best)}\n\n"
            f"**Hardest countries (logreg F1):** {line(reversed(worst))}\n\n"
            "Hard cases are mostly high-immigration / shared-script countries "
            "(US, CA, Gulf states) where names overlap heavily across borders.")


# ====================================================================================
# Layout
# ====================================================================================
THEME = gr.themes.Soft(primary_hue="indigo", neutral_hue="slate",
                       font=[gr.themes.GoogleFont("Inter"), "system-ui", "sans-serif"])

CSS = """
.gradio-container {max-width: 960px !important; margin: 0 auto !important;}
footer {display: none !important;}
#hdr {text-align: center; margin: 6px 0 0 0;}
#sub {text-align: center; color: var(--body-text-color-subdued);
      font-size: 0.92rem; margin: 2px 0 10px 0;}
#meta {text-align: center; color: var(--body-text-color-subdued); font-size: 0.85rem;}

/* revealed artifacts: a soft separator above the results */
.artifacts {border: none !important; box-shadow: none !important; background: transparent !important;
            border-top: 1px solid var(--border-color-primary) !important;
            border-radius: 0 !important; margin-top: 14px; padding-top: 14px;}

/* stat cards (EDA / Preprocess key numbers) */
.stat-cards {display: flex; flex-wrap: wrap; gap: 10px; margin: 4px 0 14px;}
.stat-cards .stat {flex: 1 1 110px; text-align: center; padding: 14px 12px;
    background: var(--block-background-fill);
    border: 1px solid var(--border-color-primary); border-radius: 12px;}
.stat-cards .stat .v {font-size: 1.35rem; font-weight: 700; line-height: 1.1;
    color: var(--body-text-color);}
.stat-cards .stat .k {margin-top: 5px; font-size: 0.7rem; font-weight: 600;
    letter-spacing: 0.04em; text-transform: uppercase;
    color: var(--body-text-color-subdued);}
.muted {color: var(--body-text-color-subdued); font-style: italic;}

/* metrics tables rendered from markdown */
.tbl table {width: 100%; border-collapse: collapse; font-size: 0.9rem;
    border: 1px solid var(--border-color-primary); border-radius: 12px; overflow: hidden;}
.tbl thead th {background: var(--table-even-background-fill, var(--neutral-100));
    text-align: left; padding: 9px 13px; font-weight: 600; border: none;}
.tbl tbody td {padding: 9px 13px; border: none;
    border-top: 1px solid var(--border-color-primary);}
.tbl tbody tr:hover {background: var(--table-row-focus, rgba(128,128,128,0.06));}

/* simulated console: a real terminal look */
.console {border-radius: 12px !important; overflow: hidden;}
.console .cm-editor, .console textarea {font-size: 0.82rem !important; line-height: 1.5 !important;}
"""

OVERVIEW = """
### A guided tour of the pipeline

This Space walks through the whole project, **one page per stage** — the same stages that
live in `pipeline/`:

| # | Page | Script | What it does |
|---|------|--------|--------------|
| 1 | **EDA** | `eda01.py` | Profile 33M raw rows + the generated splits; quantify class balance and name ambiguity |
| 2 | **Preprocess** | `preprocess02.py` | Synthesize full names, split 70/15/15, featurize to index arrays |
| 3 | **Baselines** | `baseline03.py` | Train 3 sklearn TF-IDF models as a CPU floor |
| 4 | **Evaluation** | `evaluation04.py` | Score on the held-out test set (strict + ambiguity-aware) |
| 5 | **Predict** | `predict05.py` | **Live** inference — try your own names |

On each stage page, hit **▶ Run this step** to replay that stage's console log, then see the
**pre-generated** plots and metrics it produced. (The heavy stages ran offline over millions
of rows — only **Predict** runs live here.)

📦 **Source code:** [github.com/britoddd/ml-name_country_origin_checker](https://github.com/britoddd/ml-name_country_origin_checker)

---
""" + DISCLAIMER


def build_step_tab(label, intro_md, log_lines, build_artifacts):
    """One pipeline-stage page: narration → Run button → console → revealed artifacts."""
    with gr.Tab(label):
        gr.Markdown(intro_md)
        run_btn = gr.Button("▶  Run this step", variant="primary")
        console = step_console()
        with gr.Group(visible=False, elem_classes="artifacts") as artifacts:
            build_artifacts()
        run_btn.click(make_runner(log_lines), outputs=[console, artifacts])


with gr.Blocks(title="Name → Country", theme=THEME, css=CSS) as demo:
    gr.Markdown("# 🌍  Name → Country", elem_id="hdr")
    gr.Markdown("A name-to-country classifier, presented as a walkthrough of its ML pipeline — "
                "a statistical guess from character patterns, not a fact about any person.",
                elem_id="sub")

    with gr.Tabs():
        with gr.Tab("Overview"):
            gr.Markdown(OVERVIEW)
            with gr.Accordion("About & ethics", open=False):
                gr.Markdown(
                    "**How it works.** Names are normalized to lowercase `a–z`+space and turned "
                    "into character n-gram TF-IDF features, then classified across ~104 countries "
                    "by linear models (Logistic Regression / Linear SVM / SGD; macro-F1 ≈0.50 on "
                    "held-out test). Runs on CPU.\n\n" + DISCLAIMER)

        # ---- 1 · EDA ----
        def _eda_artifacts():
            gr.Markdown("#### Dataset at a glance")
            gr.HTML(eda_stats_html())
            gr.Gallery(
                value=[
                    (_asset("eda", "eda_class_balance.png"), "Class balance (per-country counts)"),
                    (_asset("eda", "eda_name_length.png"), "Name length distribution"),
                    (_asset("eda", "eda_tokens_per_name.png"), "Tokens per name"),
                    (_asset("eda", "eda_char_frequency.png"), "Character frequency"),
                    (_asset("eda", "eda_count_distribution.png"), "Frequency-count distribution"),
                    (_asset("eda", "eda_tokens_per_country.png"), "Distinct tokens per country"),
                    (_asset("eda", "eda_multicountry.png"), "Multi-country ambiguity"),
                ],
                label="EDA figures", columns=1, height=620, object_fit="contain",
            )
            with gr.Accordion("Full EDA report (eda_report.md)", open=False):
                gr.Markdown(EDA_REPORT or "_report not bundled_")

        build_step_tab(
            "1 · EDA",
            "### Stage 1 — Exploratory Data Analysis\n"
            "Before modeling, understand the data. `eda01.py` chunk-scans the raw aggregated "
            "tables (~33M token rows, never loaded into RAM at once) and profiles the generated "
            "splits: **class balance**, **name length / token counts**, **character frequencies**, "
            "and the **multi-country ambiguity** that makes this task genuinely hard — e.g. "
            "*'ali ali'* legitimately appears in **30** countries.",
            EDA_LOG, _eda_artifacts,
        )

        # ---- 2 · Preprocess ----
        def _pre_artifacts():
            gr.Markdown("#### Resulting dataset")
            gr.HTML(pre_stats_html())
            gr.Markdown(
                "- **Synthesis.** The source tables are *aggregated frequency counts* of name "
                "tokens per country — there are no pre-joined full names. So we sample a forename "
                "and surname **weighted by their real counts** to reproduce realistic full names "
                "matching the inference contract (`\"Joko Widodo\"`).\n"
                "- **Split.** Stratified **70/15/15** per country.\n"
                "- **Ambiguity map.** `name_country_map.json` records the 174,564 names spanning "
                ">1 country — used later for *ambiguity-aware* evaluation.\n"
                "- **Featurization.** Lowercase `a–z`+space, truncate/pad to 30 chars, map to "
                "char indices — **identical to training & inference** (`common.py`)."
            )

        build_step_tab(
            "2 · Preprocess",
            "### Stage 2 — Build the dataset\n"
            "`preprocess02.py` turns the raw frequency tables into a trainable dataset: it "
            "**synthesizes** realistic full names by sampling forename ⨯ surname weighted by real "
            "popularity, makes a **stratified 70/15/15** split, builds the multi-country ambiguity "
            "map, and **featurizes** every name to a fixed-length integer index array.",
            PRE_LOG, _pre_artifacts,
        )

        # ---- 3 · Baselines ----
        def _base_artifacts():
            gr.Markdown("#### Training results (sklearn floor models)")
            gr.Markdown(baseline_table_md(), elem_classes="tbl")
            gr.Markdown(
                "Char n-gram **TF-IDF** → Logistic Regression (saga) / Linear SVM / SGD. "
                "Logistic Regression wins on macro-F1 while training in **under 3 minutes** on CPU "
                "— a strong, cheap model that trains in minutes on CPU. All three are pickled with "
                "plain sklearn so they load anywhere."
            )

        build_step_tab(
            "3 · Baselines",
            "### Stage 3 — Train the models\n"
            "`baseline03.py` fits three linear classifiers on character n-gram TF-IDF features. "
            "They're fast, CPU-only, and set the macro-F1 the project is built around — Logistic "
            "Regression is the model served on the Predict page.",
            BASE_LOG, _base_artifacts,
        )

        # ---- 4 · Evaluation ----
        def _eval_artifacts():
            gr.Markdown("#### Held-out test metrics")
            gr.Markdown(eval_table_md(), elem_classes="tbl")
            gr.Markdown(
                "**Strict** = exact country match. **Set-lenient top-1** credits a prediction that "
                "hits *any* country the name legitimately belongs to (via the ambiguity map) — it "
                "rises ~4 points, quantifying how much error is really just name ambiguity."
            )
            gr.Gallery(
                value=[
                    (_asset("evaluation", "model_comparison_macro_f1.png"), "Model comparison (macro-F1)"),
                    (_asset("evaluation", "per_country_f1_logreg.png"), "Per-country F1 (logreg)"),
                    (_asset("evaluation", "confusion_matrix_logreg.png"), "Confusion matrix (logreg)"),
                ],
                label="Evaluation figures", columns=1, height=620, object_fit="contain",
            )
            gr.Markdown(per_country_md())

        build_step_tab(
            "4 · Evaluation",
            "### Stage 4 — Evaluate on the held-out test set\n"
            "`evaluation04.py` scores each model on 776K unseen names with **strict macro-F1** "
            "(primary), accuracy, top-3/5, MRR and NLL — plus an **ambiguity-aware** set-lenient "
            "score that credits any country a name truly belongs to, and **per-country F1** to see "
            "where the model struggles.",
            EVAL_LOG, _eval_artifacts,
        )

        # ---- 5 · Predict (LIVE) ----
        with gr.Tab("5 · Predict"):
            gr.Markdown(
                "### Stage 5 — Live inference\n"
                "This page runs for real. Enter a name for top-k countries, or upload a CSV for "
                "batch scoring. Same featurization as every stage above.")
            with gr.Tab("Single"):
                name_in = gr.Textbox(show_label=False, autofocus=True, lines=1,
                                     placeholder="Enter a full name…   e.g.  Joko Widodo")
                run_btn = gr.Button("Predict", variant="primary")
                label_out = gr.Label(show_label=False, num_top_classes=10)
                info_out = gr.Markdown(elem_id="meta")

            with gr.Tab("Batch"):
                gr.Markdown("Upload a CSV with a **`name`** column (or names in the first column).",
                            elem_id="sub")
                file_in = gr.File(show_label=False, file_types=[".csv"])
                batch_btn = gr.Button("Predict batch", variant="primary")
                batch_msg = gr.Markdown(elem_id="meta")
                batch_table = gr.Dataframe(show_label=False, wrap=True)
                batch_file = gr.File(label="Download predictions")

            with gr.Accordion("⚙️  Options", open=False):
                backend = gr.Radio(choices=list(BACKENDS.keys()), value=DEFAULT_BACKEND,
                                   label="Model backend")
                top_k = gr.Slider(1, 10, value=5, step=1, label="Top-k countries")

            run_btn.click(predict_single, [name_in, backend, top_k], [label_out, info_out])
            name_in.submit(predict_single, [name_in, backend, top_k], [label_out, info_out])
            batch_btn.click(predict_batch, [file_in, backend, top_k],
                            [batch_table, batch_file, batch_msg])


if __name__ == "__main__":
    demo.launch()
